// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVgP2Tpg09dHxHL-96d2aUyfbn5wwrz-c',
    appId: '1:507428226500:web:da04e44b8b5d515eb99091',
    messagingSenderId: '507428226500',
    projectId: 'ticketflutter-fc009',
    authDomain: 'ticketflutter-fc009.firebaseapp.com',
    storageBucket: 'ticketflutter-fc009.firebasestorage.app',
    measurementId: 'G-3GR2WKYQHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAIbTK6D6MDL8c_jmbu1YfA-Exn124maQ',
    appId: '1:507428226500:android:23e0ce084ae5e8dcb99091',
    messagingSenderId: '507428226500',
    projectId: 'ticketflutter-fc009',
    storageBucket: 'ticketflutter-fc009.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0hSt3aKtAl1jsG-D97ZEYqW7VjODU7IM',
    appId: '1:507428226500:ios:f3bfa062f15a86bfb99091',
    messagingSenderId: '507428226500',
    projectId: 'ticketflutter-fc009',
    storageBucket: 'ticketflutter-fc009.firebasestorage.app',
    iosBundleId: 'com.example.ticketFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0hSt3aKtAl1jsG-D97ZEYqW7VjODU7IM',
    appId: '1:507428226500:ios:f3bfa062f15a86bfb99091',
    messagingSenderId: '507428226500',
    projectId: 'ticketflutter-fc009',
    storageBucket: 'ticketflutter-fc009.firebasestorage.app',
    iosBundleId: 'com.example.ticketFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVgP2Tpg09dHxHL-96d2aUyfbn5wwrz-c',
    appId: '1:507428226500:web:d3d572b6c1ad5449b99091',
    messagingSenderId: '507428226500',
    projectId: 'ticketflutter-fc009',
    authDomain: 'ticketflutter-fc009.firebaseapp.com',
    storageBucket: 'ticketflutter-fc009.firebasestorage.app',
    measurementId: 'G-L971Q124HT',
  );
}
